### PR TITLE
Update to 1.20 + mixin refactor

### LINKED ISSUE #2: Port mod to 1.20.1
This mod is pretty great for community SMP servers. I myself used to use it in mine, but ever since we updated to 1.20, we can't use it anymore. It would be nice of the mod could get updated as well.

### PR DESCRIPTION
**Pull request by unilock**
This PR updates the mod to 1.20.1, as well as refactors the mixins and makes a bunch of other small changes (mostly IDE recommendations).

- Gradle updated to 8.3
- Fabric Loom updated to 1.3
- Mod version now includes target Minecraft version (while respecting SemVer) - i.e. `1.3.0+1.20.1` instead of just `1.3.0`
- The mod will once again initialize on the client if installed there, in the case that the user wants to use it in an "Open to LAN" singleplayer world or something
- ~~All commands now `return 0;`, as that's typically the exit code of successful commands~~ Apparently it's `1` with Brigadier, according to `Command.SINGLE_SUCCESS`
- `CommandMixin` has been renamed to `ServerPlayerEntityMixin` and no longer `extends PlayerEntity`, which was unnecessary
- `PhantomSpawnerMixin` is now much simpler in that it uses only a single `@Inject` into the beginning of the `ServerPlayerEntity` iterator that captures locals and sets the return value of the `spawn` method prematurely, instead of using two `@ModifyVariable`s and utilizing a unique (`PlayerEntity`) field
- The icon is now 1.33 KiB (16%) smaller, wow!!

Fixes #2.

Probably functionally identical to #3, but I haven't tested it, and this PR has other benefits regardless.

Also, a new branch (`1.20`) should probably be made.

### CODE REVIEW

**Comment by ArkoSammy12** [comment]
Hello. Just asking if I can build off of this PR to make another for 1.20.2

**Comment by unilock** [comment]
@ArkoSammy12 Sure! I see you also [made a fork](https://github.com/ArkoSammy12/freedom-of-insomnia/commit/3222cde43e5ca19c9f5973675ab33f23bcb66b8b) that prevents phantoms from targeting players with insomnia disabled; I think that's a good change, too.

**Comment by ArkoSammy12** [comment]
> @ArkoSammy12 Sure! I see you also [made a fork](https://github.com/ArkoSammy12/freedom-of-insomnia/commit/3222cde43e5ca19c9f5973675ab33f23bcb66b8b) that prevents phantoms from targeting players with insomnia disabled; I think that's a good change, too.

Awesome, thank you so much :D

**Comment by ArkoSammy12** [comment]
Seems like the mod builds successfully on 1.20.2, with no code changes required. The Minecraft version dependency is already set to `>=1.20.1` so I would suggest changing the name of your PR to state that it also supports 1.20.2.

**Comment by ArkoSammy12** [comment]
Wow, you are still contributing to this mod :o

**Comment by unilock** [comment]
i just wanted it for my private 1.20.4 server lol

**Comment by ArkoSammy12** [comment]
> i just wanted it for my private 1.20.4 server lol

Xd. I get it haha. In my case I ended up making my own take on the mod from scratch.

**Comment by SerenModz21** [comment]
nice pr! i've been working on updating a private server i manage, to 1.20 so thought about updating it myself but this pr saves me sometime alongside making it available to other people also. thank you!

**Comment by cqm3ron** [comment]
Any chance of a 1.20.6 fork and a 1.21 fork when that releases?

**Comment by ArkoSammy12** [comment]
> Any chance of a 1.20.6 fork and a 1.21 fork when that releases?

I'm not sure, but I do plan to update my [Sensible Sleepiness](https://www.modrinth.com/mod/sensible-sleepiness) mod to those versions soon :)

**Comment by were491** [comment]
Sorry, I legitimately don't know what to do with this PR considering I haven't touched modding or anything git-related in years. I'm glad you've all seemed to find a way to continue the work though xD

**Pull request closed without merging**
